# Generated by Django 3.0.1 on 2020-05-18 16:26

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('BKASH', 'bkash'), ('ROCKET', 'rocket'), ('BANK', 'bank')], max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('token', models.IntegerField(blank=True, null=True)),
                ('transaction', models.CharField(max_length=100, unique=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('paymented', models.BooleanField(default=False)),
                ('admin_verify', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Order')),
            ],
        ),
    ]
