# Generated by Django 3.0.1 on 2020-05-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentApp', '0003_auto_20200518_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='admin_verify',
            new_name='payment_verify',
        ),
    ]
