# Generated by Django 3.0.1 on 2020-05-18 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_order_billing_address'),
        ('PaymentApp', '0004_auto_20200518_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.Order'),
        ),
    ]
