# Generated by Django 3.0.1 on 2020-05-20 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentApp', '0005_auto_20200518_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paymented',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='token',
        ),
    ]
